import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import ModeToggle from "@/components/ModeToggle";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  display: "swap",
});
export const metadata: Metadata = {
  title: "Rainer Morales | Porfolio",
  description: "Generated by create next app",
  icons: "Profile.jpg",
};
const dates = new Date();
const years = dates.getFullYear();
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={roboto.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          {children}
          <ModeToggle />
        </ThemeProvider>
        <footer className="border-t text-center p-4 opacity-60 text-sm">
          <div>&copy; {years} Rainer Morales. All rights reserve</div>
          <div>Made with 💖</div>
        </footer>
      </body>
    </html>
  );
}
